learning_log/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('learning_logs.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('api-auth/', include('rest_framework.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learning_logs/urls.py
from django.urls import include, path

from rest_framework import routers

from .views import (
    IndexView,
    TagListView,
    TagCreateView,
    EntryListView,
    EntryNewestListView,
    EntryTopListView,
    EntryTagListView,
    EntryCreateView,
    EntryDetailView,
    EntryLikeView,
    EntryUpdateView,
    EntryDeleteView,
    CommentCreateView,
    CommentUpdateView,
    CommentDeleteView
)

from learning_logs import views

router = routers.DefaultRouter()
router.register(r'tags', views.TagViewSet)

app_name = 'learning_logs'

urlpatterns = [
    path('api-tag/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', IndexView.as_view(), name='index'),
    path('tags/', TagListView.as_view(), name='tags'),
    path('tag/add/', TagCreateView.as_view(), name='tag_create'),
    path('entries/', EntryListView.as_view(), name='entries'),
    path('new/', EntryNewestListView.as_view(), name='newest'),
    path('top/', EntryTopListView.as_view(), name='top'),
    path('tag/<slug:slug>/', EntryTagListView.as_view(), name='tag'),
    path('entry/add/', EntryCreateView.as_view(), name='entry_create'),
    path('entry/<slug:slug>/', EntryDetailView.as_view(), name='entry'),
    path('entry/<slug:slug>/like/', EntryLikeView.as_view(), name='entry_like'),
    path('entry/<slug:slug>/update/', EntryUpdateView.as_view(), name='entry_update'),
    path('entry/<int:pk>/delete/', EntryDeleteView.as_view(), name='entry_delete'),
    path('entry/<slug:slug>/comment/add/', CommentCreateView.as_view(), name='comment_create'),
    path('comment/<int:pk>/update/', CommentUpdateView.as_view(), name='comment_update'),
    path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment_delete'),
]

users/urls.py
from django.urls import path

from .views import (
    LoginView,
    LogoutView,
    RegisterView,
    ProfileDetailView,
    ProfileUpdateView,
    ProfileDeleteView
)

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileDetailView.as_view(), name='profile'),
    path('profile/update/', ProfileUpdateView.as_view(), name='profile_update'),
    path('delete/', ProfileDeleteView.as_view(), name='profile_delete'),
]

users/models.py
from django.contrib.auth.models import User
from django.db import models


class Person(models.Model):
    MALE = 'male'
    FEMALE = 'female'
    SEX_CHOICES = (
        (MALE, 'male'),
        (FEMALE, 'female'),
    )
    owner = models.OneToOneField(User, on_delete=models.CASCADE, related_name='person')
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    sex = models.CharField(max_length=6, choices=SEX_CHOICES, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    home_page = models.URLField(null=True, blank=True)
    image = models.ImageField(upload_to='users/img', default='', blank=True)

    def __str__(self):
        return str(self.owner)

users/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Person


class UserForm(forms.ModelForm):
    
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email'
        ]


class PersonForm(forms.ModelForm):

    class Meta:
        model = Person
        exclude = ('owner',)
        labels = {
            'first_name': 'First name:',
            'last_name': 'Last name:',
            'sex': 'Genger',
            'birth_date': 'Birth date',
            'email': 'E-mail',
            'home_page': 'Home page',
            'about_me': 'About me',
            'image': 'Photo'
        }
        widgets = {
            'first_name': forms.TextInput(attrs={
                'class': 'form-control',
                'required': 'required',
                'placeholder': 'Enter your first name'
            }),
            'last_name': forms.TextInput(attrs={
                'class': 'form-control',
                'required': 'required',
                'placeholder': 'Enter your last name'
            }),
            'sex': forms.Select(attrs={
                'class': 'form-control',
                'required': 'required'
            }),
            'birth_date': forms.DateInput(attrs={
                'type': 'date',
                'class': 'form-control',
                'placeholder': 'Enter your birthdate'
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter your e-mail'
            }),
            'home_page': forms.URLInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter your home page URL'
            }),
            'about_me': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Tell us about yourself...'
            }),
            'image': forms.FileInput(attrs={
                'class': 'form-control'
            })
        }

users/views.py
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.base import View, TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, FormView, UpdateView
from django.views.generic.list import ListView
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy

from .models import Person
from .forms import PersonForm, UserForm


class LoginView(FormView):
    template_name = 'users/login.html'
    form_class = AuthenticationForm
    success_url = reverse_lazy('users:profile')

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Log In'
        return context


class LogoutView(View):

    def get(self, request):
        logout(request)
        return redirect('learning_logs:index')


class RegisterView(FormView):
    template_name = 'users/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('learning_logs:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Register'
        return context

    def form_valid(self, form):
        form.save()
        login(self.request, authenticate(
            username=form.cleaned_data['username'],
            password=form.cleaned_data['password1']
        ))
        
        # Create Person model
        obj = Person.objects.get_or_create(owner=self.request.user)[0]
        obj.save()
        
        # Display message
        msg = 'Account {} was registered successfully'.format(self.request.user.username)
        messages.success(self.request, msg)
        return super().form_valid(form)


class ChangePasswordView():
    pass
    

class ProfileDetailView(LoginRequiredMixin, TemplateView):
    template_name = 'users/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.request.user.username
        return context


class ProfileUpdateView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        return render(request, 'users/profile_update.html', {
            'form': PersonForm(instance=request.user.person),
            'title': request.user.username
        })
        
    def post(self, request, *args, **kwargs):
        user = self.request.user
        form = PersonForm(instance=user.person, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your profile was updated successfully')
            return redirect('users:profile')
        return render(request, 'users/profile_update.html', {
            'form': form,
            'title': user.username
        })
    

class ProfileDeleteView(View):
    pass

users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
  <section class="card">
    <div class="card-header">
        <h2>Log In</h2>
    </div>
    <div class="card-body">
    <form action="" method="post" class="form-signin">
          {% csrf_token %}
          <div class="mb-3">
            <label for="id_username" class="form-label">Username</label>
            <input type="text" name="username" required autofocus maxlength="254" id="id_username" class="form-control" placeholder="username">
            {{ form.username.errors }}
          </div>
          <div class="mb-3">
            <label for="id_password" class="form-label">Password</label>
            <input type="password" id="id_password" class="form-control" name="password" required placeholder="password">
            {{ form.password.errors }}
          </div>
          <button type="submit" class="btn btn-primary">Log In</button>
          <a href="{% url 'users:register' %}" class="btn btn-link">Register</a>
        </form>
    </div>
  </section>
{% endblock %}

users/templates/users/person_form.html
{% extends 'base.html' %}

{% block breadcrumb %}
<header class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'learning_logs:index' %}">Home</a></li>
      <li class="breadcrumb-item"><a href="{% url 'users:profile' request.user.person.id %}">Profile</a></li>
      <li class="breadcrumb-item active">{{ title }}</li>
    </ol>
  </nav>
</header>
{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col">
      <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
          {{ form.first_name.label_tag }}
          {{ form.first_name }}
          {{ form.first_name.errors }}
        </div>
        <div class="form-group">
          {{ form.last_name.label_tag }}
          {{ form.last_name }}
          {{ form.last_name.errors }}          
        </div>
        <div class="form-group">
          {{ form.sex.label_tag }}
          {{ form.sex }}
          {{ form.sex.errors }}          
        </div>
        <div class="form-group">
          {{ form.birth_date.label_tag }}
          {{ form.birth_date }}
          {{ form.birth_date.errors }}          
        </div>
        <div class="form-group">
          {{ form.email.label_tag }}
          {{ form.email }}
          {{ form.email.errors }}          
        </div>
        <div class="form-group">
          {{ form.home_page.label_tag }}
          {{ form.home_page }}
          {{ form.home_page.errors }}          
        </div>
        <div class="form-group">
          {{ form.about_me.label_tag }}
          {{ form.about_me }}
          {{ form.about_me.errors }}          
        </div>
        <div class="form-group">
          {{ form.image.label_tag }}
          {{ form.image }}
          {{ form.image.errors }}          
        </div>
        <input type="submit" class="btn btn-primary" value="Submit">
      </form>
    </div>
  </div>
</div>
<br>
{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% with person=request.user.person %}
<div class="card">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-bs-toggle="tab" href="#profile">Profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-bs-toggle="tab" href="#entries">Entries</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-bs-toggle="tab" href="#comments">Comments</a>
            </li>
        </ul>
    </div>

    <div class="card-body">
        <div class="tab-content">
          <div class="tab-pane fade show active" id="profile">
            <img 
                src="{% if person.image %}{{ person.image.url }}{% else %}{% static 'img/avatar-tiny.jpg' %}{% endif %}" 
                class="rounded float-start mb-3"
            >
            <table class="table table-bordered">
              <tbody>
                <tr><td><b>First name</b></td><td>{{ person.first_name }}</td></tr>
                <tr><td><b>Last name</b></td><td>{{ person.last_name }}</td></tr>
                <tr><td><b>Sex</b></td><td>{{ person.sex }}</td></tr>
                <tr><td><b>Birth date</b></td><td>{{ person.birth_date|default:"" }}</td></tr>
                <tr><td><b>Email</b></td><td>{{ person.email|default:"" }}</td></tr>
                <tr><td><b>Home page</b></td><td>{{ person.home_page|default:"" }}</td></tr>
              </tbody>
            </table>
            <a href="{% url 'users:profile_update' %}" class="btn btn-link">Update</a>
          </div><!-- /#profiel -->
          <div class="tab-pane fade" id="entries">
            <a href="{% url 'learning_logs:entry_create' %}" class="btn btn-success mb-2">
                <i class="fas fa-plus-circle"></i>
                Add
            </a>
            <table class="table table-bordered">
              <thead>
                <tr>
                  <th>Title</th>
                  <th class="text-center">Date added</th>
                  <th class="text-center">Views</th>
                  <th class="text-center">Likes</th>
                  <th class="text-center">Comments</th>
                  <th class="text-center">Update</th>
                  <th class="text-center">Delete</th>
                </tr>
              </thead>
              <tbody>
                {% for entry in person.owner.entry.all %}
                  <tr>
                    <td><a href="{% url 'learning_logs:entry' entry.slug %}">{{ entry.title }}</a></td>
                    <td class="text-center">{{ entry.date_added|date:'d.m.Y' }}</td>
                    <td class="text-center">{{ entry.views }}</td>
                    <td class="text-center">{{ entry.likes }}</td>
                    <td class="text-center">{{ entry.comments }}</td>
                    <td class="text-center">
                        <a href="{% url 'learning_logs:entry_update' entry.slug %}" class="btn btn-outline-primary btn-sm">
                            Update
                        </a>
                    </td>
                    <td class="text-center">
                        <button type="button" data-toggle="modal" data-target="#entryDelete{{forloop.counter}}" class="btn btn-outline-danger btn-sm">
                            Delete
                        </button>
                        
                        <!-- The Modal -->
                        <div class="modal fade" id="entryDelete{{forloop.counter}}">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    
                                    <!-- Modal Header -->
                                    <div class="modal-header">
                                        <h4 class="modal-title">Deleting An Article</h4>
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    </div><!-- /.modal-header -->
                                
                                    <!-- Modal Body -->
                                    <div class="modal-body">
                                        Do you want to delete an article: {{ entry.title }}
                                    </div><!-- /.modal-body -->
                                    
                                    <!-- Modal Footer -->
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        <form action="{% url 'learning_logs:entry_delete' entry.pk %}" method="post">
                                            {% csrf_token %}
                                            <button type=submit class="btn btn-danger">Delete</button>
                                        </form>
                                    </div><!-- /.modal-footer -->
                                    
                                </div><!-- /.modal-content -->
                            </div><!-- /.modal-dialog -->
                        </div><!-- /.modal -->
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div><!-- /#entries -->
          <div class="tab-pane fade" id="comments">
            <br>
            <table class="table table-bordered">
              <thead>
                <tr>
                  <th class="text-left">Comment</th>
                  <th class="text-left">Entry</th>
                  <th class="text-center">Date added</th>
                  <th class="text-center">Delete</th>
                </tr>
              </thead>
              <tbody>
                {% for comment in person.owner.comment.all %}
                  <tr>
                    <td class="text-left"><a href="{% url 'learning_logs:entry' comment.entry.slug %}">{{ comment.text|truncatewords:5 }}</a></td>
                    <td class="text-left">{{ comment.entry.title }}</td>
                    <td class="text-center">{{ comment.date_added|date:'d.m.Y' }}</td>
                    <td class="text-center">
                        <button type="button" data-toggle="modal" data-target="#commentDelete{{forloop.counter}}" class="btn btn-outline-danger btn-sm">
                            Delete
                        </button>
                        
                        <!-- The Modal -->
                        <div class="modal fade" id="commentDelete{{forloop.counter}}">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    
                                    <!-- Modal Header -->
                                    <div class="modal-header">
                                        <h4 class="modal-title">Deleting A Comment</h4>
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    </div><!-- /.modal-header -->
                                
                                    <!-- Modal Body -->
                                    <div class="modal-body">
                                        Do you want to delete a comment: {{ comment.text }}
                                    </div><!-- /.modal-body -->
                                    
                                    <!-- Modal Footer -->
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        <form action="{% url 'learning_logs:comment_delete' comment.pk %}" method="post">
                                            {% csrf_token %}
                                            <button type=submit class="btn btn-danger">Delete</button>
                                        </form>
                                    </div><!-- /.modal-footer -->
                                    
                                </div><!-- /.modal-content -->
                            </div><!-- /.modal-dialog -->
                        </div><!-- /.modal -->
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div><!-- /#comments -->
        </div><!-- /.tab-content -->
      </div><!-- /.col -->
</div><!-- /.container -->
{% endwith %}
{% endblock %}

users/templates/users/profile_update.html
{% extends 'base.html' %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'users:profile' %}">Profile</a></li>
{% endblock %}

{% block content %}
<div class="card">
    <div class="card-header">
        <h2>Edit profile</h2>
    </div>
    <div class="card-body">
      <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
          {{ form.first_name }}
          {{ form.first_name.errors }}
        </div>
        <div class="mb-3">
          {{ form.last_name }}
          {{ form.last_name.errors }}          
        </div>
        <div class="mb-3">
          {{ form.sex }}
          {{ form.sex.errors }}          
        </div>
        <div class="mb-3">
          {{ form.birth_date }}
          {{ form.birth_date.errors }}          
        </div>
        <div class="mb-3">
          {{ form.email }}
          {{ form.email.errors }}          
        </div>
        <div class="mb-3">
          {{ form.home_page }}
          {{ form.home_page.errors }}          
        </div>
        <div class="mb-3">
          {{ form.image }}
          {{ form.image.errors }}          
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
      </form>
    </div>
  </div>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
  <section class="card">
    <div class="card-header">
        <h2>Register</h2>
    </div>
    <div class="card-body">
    <form action="" method="post" class="form-signin">
      {% csrf_token %}
      <div class="mb-3">
        <label for="id_username" class="form-label">Username</label>
        <input type="text" name="username" required autofocus id="id_username" maxlength="150" class="form-control" placeholder="Enter username">
        {{ form.username.errors }}
      </div>
      <div class="mb-3">
        <label for="id_password1" class="form-label">Password</label>
        <input type="password" name="password1" required id="id_password1" class="form-control" placeholder="Enter password">
        {{ form.password1.errors }}
      </div>
      <div class="mb-3">
        <label for="id_password2" class="form-label">Confirm password</label>
        <input type="password" name="password2" required id="id_password2" class="form-control" placeholder="Repeat password">
        {{ form.password2.errors }}
      </div>
        <button type="submit" class="btn btn-primary">Register</button>
        <a href="{% url 'users:login' %}" class="btn btn-link">Login</a>
    </form>
    </div>
  </section>
{% endblock %}